version: "2"

build:
  os: "ubuntu-22.04"
  tools:
     python: "mambaforge-22.9"
  jobs:
     post_create_environment:
       - pip install -r docs/requirements.txt
       - pip install .

conda:
  environment: environment.yml

    
sphinx:
  configuration: docs/source/conf.py
